### ISSUE TITLE
Dialog Modal com SelectOneMenu - problema ao renderizar itens

### ISSUE THREAD

**Issue by ghost** [adminfaces/admin-starter-tomcat#2]
Estou usando o SelectOneMenu, sem conexão ao managedBean, quando selecione ele os itens são mostrados atras do Dialog,

Version: 1.0.0-RC18
Primefaces: 6.2
Primefaces Extensions: 6.0.0
Omnifaces: 2.6.1

<p:dialog header="Manutenção de Usuário" 
		widgetVar="registroSelecionado"
		draggable="false"
		resizable="false"
		modal="true" 
		closable="false"
		appendToBody="false"
		ajax="false">
	<h:form id="frmCadastro">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h:panelGrid id="pnlCadastro" columns="2">

					<p:outputLabel for="nome" value="Nome:" />
					<p:inputText 
						id="nome"
						maxlength="50" 
						size="50" 
						value="#{usuarioMB.usuarioSelecionado.nome}" 
						required="true" 
						requiredMessage="Campo obrigatório" 
						style="margin: 10px 0 0 10px;"/>

					<p:outputLabel for="email" value="Email:" />
					<p:inputText 
						id="email"
						maxlength="200" 
						size="80" 
						value="#{usuarioMB.usuarioSelecionado.email}"
						required="true" 
						requiredMessage="Campo obrigatório" 
						style="margin: 10px 0 0 10px;"/>

					<p:outputLabel for="senha1" value="Senha:" />
					<p:password
						id="senha1"
						maxlength="32" 
						size="30" 
						value="#{usuarioMB.usuarioSelecionado.senha}"
						required="true" 
						requiredMessage="Campo obrigatório" 
						style="margin: 10px 0 0 10px;"
						match="senha2"/>

					<p:outputLabel for="senha2" value="Redigite:" />
					<p:password
						id="senha2"
						maxlength="32" 
						size="30" 
						value="#{usuarioMB.usuarioSelecionado.senha}"
						required="true" 
						requiredMessage="Campo obrigatório" 
						style="margin: 10px 0 0 10px;" />
				  
					<p:outputLabel for="ativo" value="Ativo:" />
					<p:selectBooleanButton 
						id="ativo" 
						value="#{usuarioMB.usuarioSelecionado.ativo}"
						onLabel="Sim" 
						offLabel="Não" 
						style="margin: 10px 0 0 10px; width: 60px;" />
						
					<p:outputLabel for="tipo2" value="Tipo:" />
					<p:selectOneMenu
						id="tipo2" 
						value="#{usuarioMB.usuarioSelecionado.usuarioTipo}"
						style="margin: 10px 0 0 10px;" 
						ajax="false">
						<f:selectItem itemLabel="Selecione" />
						<f:selectItem itemLabel="Administrador" itemValue="ADM" />
						<f:selectItem itemLabel="Gerente"       itemValue="GER" />
						<f:selectItem itemLabel="Comprador"     itemValue="COM" />
						<f:selectItem itemLabel="Vendedor"      itemValue="VEN" />
					</p:selectOneMenu>
					
				</h:panelGrid>
				<p:spacer width="30"/>
				<h:panelGrid columns="3">
					<p:commandButton 
						styleClass="btn-info"
						icon="fa fa-check"  
						value="Salvar" 
						actionListener="#{usuarioMB.salvar}"
						oncomplete="PF('registroSelecionado').hide();"
						update=":frmListagem :frmListagem:tblRegistro"
						/>
					<p:spacer width="20"/>
					<p:commandButton 
						styleClass="btn-danger"
						icon="fa fa-close" 
						value="Cancelar" 
						oncomplete="PF('registroSelecionado').hide();"/>
				</h:panelGrid>
			</div>
		</div>
	</h:form>
	
</p:dialog>

**Comment by rmpestano** [comment]
Usa appentTo="@(body)" para resolver.

**Comment by ghost** [comment]
No Dialog já coloquei é não funcionou.

Outra dica?

**Comment by ghost** [comment]
Só para complementar, depois que fecho o modal, o selectOneMenu permanece na tela.

**Comment by rmpestano** [comment]
Compara com o exemplo (login dialog) do Showcase: http://admin-showcase-admin-showcase.7e14.starter-us-west-2.openshiftapps.com/showcase/pages/components/dialog.xhtml

Ainda, se você puder compartilhar um projeto que reproduz o problema eu posso ajudar melhor.

**Comment by ghost** [comment]
Segue o projeto. 

[sgc.zip](https://github.com/adminfaces/admin-starter-tomcat/files/2411633/sgc.zip)

**Comment by rmpestano** [comment]
Hi, could not run your application here, probably because of the database configuration. Please, reduce your issue to a simple project, preferable using admin-starter archetype. Or fork admin-starer project and add the reproducer there. I don't have time to configure every type of project and server to run here. 

PS: Looking at the code it looks ok, I would try to use `dynamic=true` on the dialog.

**Comment by ghost** [comment]
Seguinte havia testado no Chrome apenas, agora rodei o mesmo no Firefox e funciona. é alguma incompatibilidade com o Chrome.

**Comment by rmpestano** [comment]
Se conseguir isolar o problema em um projeto que eu possa rodar aqui (ex: no admin-starter) eu posso tentar resolver.

**Comment by ghost** [comment]
Apenas limpei o cache do chrome e funcionou. Coisa de loko.  Mas como mexi em muitas coisas vou refazer o processo inversor para causar o erro novamente e dai de passo.

**Comment by ghost** [comment]
Mais uma dúvida envolvendo o omnifaces e o selectOneMenu
 tenho o SelectOneMenu assim:

<p:selectOneMenu 
    id="estadoCombo" 
    filter="true"
    value="#{cidadeMB.cidadeSelecionado.estado}"
    converter="omnifaces.SelectItemsConverter"
    style="margin: 10px 0 0 10px;">
    <f:selectItem 
        itemLabel="Selecione um estado"
        noSelectionOption="true" />
    <f:selectItems 
        value="#{cidadeMB.estados}" 
        var="estado"
        ItemValue="#{estado}" 
        ItemLabel="#{estado.nome}" />
</p:selectOneMenu>


O metodo toString reescrevi como tem no site do Omnifaces:

	@Override
	public String toString() {
		return String.format("%s[id=%d]", getClass().getSimpleName(), getId());
	}


mesmo assim o SelectOneMenu retorna o seguinte no combo:
Estado[25]


Foi mudado alguma coisa no AdminFaces que influencia o toString. Usava este codigo em outro projeto sem AdminFaces e funcionava OK.


Obrigado

**Comment by rmpestano** [comment]
Pode ser a versão que você usava do OmniFaces ser diferente da que vem com o AdminFaces (2.1). 

Tu pode usar maven exclusion para remover o OmniFaces que o AdminFaces tras e declarar outra versão para ver se resolve.
